sonar.projectKey=arquitectura-software
sonar.projectName=Arquitectura de Software
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/tests/**

sonar.host.url=http://localhost:9000
sonar.token=admin
